/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing SearchOptions.
 */
export interface SearchOptions {
  searchKeyword?: string;
  /**
   * Possible values include: 'interface', 'capabilityModel'
   */
  modelFilterType?: ModelFilterType;
  continuationToken?: string;
  pageSize?: number;
}

/**
 * An interface representing ModelInformation.
 */
export interface ModelInformation {
  comment?: string;
  description?: string;
  displayName?: string;
  urnId?: string;
  modelName?: string;
  version?: number;
  /**
   * Possible values include: 'interface', 'capabilityModel'
   */
  type?: Type;
  etag?: string;
  publisherId?: string;
  publisherName?: string;
  createdOn?: Date;
  updatedOn?: Date;
}

/**
 * An interface representing SearchResponse.
 */
export interface SearchResponse {
  continuationToken?: string;
  results?: ModelInformation[];
}

/**
 * An interface representing DigitalTwinRepositoryServiceOptions.
 */
export interface DigitalTwinRepositoryServiceOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface DigitalTwinRepositoryServiceGetModelOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Private repository id. To access global repository, caller should not specify this value.
   */
  repositoryId?: string;
  /**
   * Optional. Provides a client-generated opaque value that is recorded in the logs. Using this
   * header is highly recommended for correlating client-side activities with requests received by
   * the server.
   */
  xMsClientRequestId?: string;
  /**
   * Indicates whether to expand the capability model's interface definitions inline or not. This
   * query parameter ONLY applies to Capability model. Default value: false.
   */
  expand?: boolean;
}

/**
 * Optional Parameters.
 */
export interface DigitalTwinRepositoryServiceCreateOrUpdateModelOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Private repository id. To access global repository, caller should not specify this value.
   */
  repositoryId?: string;
  /**
   * Optional. Provides a client-generated opaque value that is recorded in the logs. Using this
   * header is highly recommended for correlating client-side activities with requests received by
   * the server.
   */
  xMsClientRequestId?: string;
  /**
   * Used to make operation conditional for optimistic concurrency. That is, the document is
   * updated only if the specified etag matches the current version in the database. The value
   * should be set to the etag value of the resource.
   */
  ifMatch?: string;
}

/**
 * Optional Parameters.
 */
export interface DigitalTwinRepositoryServiceDeleteModelOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Optional. Provides a client-generated opaque value that is recorded in the logs. Using this
   * header is highly recommended for correlating client-side activities with requests received by
   * the server.
   */
  xMsClientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface DigitalTwinRepositoryServiceSearchModelOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Private repository id. To access global repository, caller should not specify this value.
   */
  repositoryId?: string;
  /**
   * Optional. Provides a client-generated opaque value that is recorded in the logs. Using this
   * header is highly recommended for correlating client-side activities with requests received by
   * the server..
   */
  xMsClientRequestId?: string;
}

/**
 * Defines headers for GetModel operation.
 */
export interface GetModelHeaders {
  /**
   * This header is generated by server and uniquely identifies the request that was made and can
   * be used for troubleshooting the request.
   */
  xMsRequestId: string;
  /**
   * Etag of the model definition.
   */
  eTag: string;
  /**
   * Id of the model returned.
   */
  xMsModelId: string;
  /**
   * Publisher's AAD tenant Id of the model returned.
   */
  xMsModelPublisherId: string;
  /**
   * Publisher's AAD tenant name of the model returned.
   */
  xMsModelPublisherName: string;
  /**
   * ISO8601 timestamp of the creation time of the model returned.
   */
  xMsModelCreatedon: Date;
  /**
   * ISO8601 timestamp of the last update time of the model returned.
   */
  xMsModelLastupdated: Date;
}

/**
 * Defines headers for CreateOrUpdateModel operation.
 */
export interface CreateOrUpdateModelHeaders {
  /**
   * This header is generated by server and uniquely identifies the request that was made and can
   * be used for troubleshooting the request.
   */
  xMsRequestId: string;
  /**
   * Etag of the model definition.
   */
  eTag: string;
}

/**
 * Defines headers for DeleteModel operation.
 */
export interface DeleteModelHeaders {
  /**
   * This header is generated by server and uniquely identifies the request that was made and can
   * be used for troubleshooting the request.
   */
  xMsRequestId: string;
}

/**
 * Defines headers for SearchModel operation.
 */
export interface SearchModelHeaders {
  /**
   * This header is generated by server and uniquely identifies the request that was made and can
   * be used for troubleshooting the request.
   */
  xMsRequestId: string;
}

/**
 * Defines values for ModelFilterType.
 * Possible values include: 'interface', 'capabilityModel'
 * @readonly
 * @enum {string}
 */
export type ModelFilterType = 'interface' | 'capabilityModel';

/**
 * Defines values for Type.
 * Possible values include: 'interface', 'capabilityModel'
 * @readonly
 * @enum {string}
 */
export type Type = 'interface' | 'capabilityModel';

/**
 * Contains response data for the getModel operation.
 */
export type GetModelResponse = GetModelHeaders & {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: GetModelHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the createOrUpdateModel operation.
 */
export type CreateOrUpdateModelResponse = CreateOrUpdateModelHeaders & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: CreateOrUpdateModelHeaders;
    };
};

/**
 * Contains response data for the deleteModel operation.
 */
export type DeleteModelResponse = DeleteModelHeaders & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: DeleteModelHeaders;
    };
};

/**
 * Contains response data for the searchModel operation.
 */
export type SearchModelResponse = SearchResponse & SearchModelHeaders & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: SearchModelHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SearchResponse;
    };
};
