/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const SearchOptions: msRest.CompositeMapper = {
  serializedName: "SearchOptions",
  type: {
    name: "Composite",
    className: "SearchOptions",
    modelProperties: {
      searchKeyword: {
        serializedName: "searchKeyword",
        type: {
          name: "String"
        }
      },
      modelFilterType: {
        serializedName: "modelFilterType",
        type: {
          name: "String"
        }
      },
      continuationToken: {
        serializedName: "continuationToken",
        type: {
          name: "String"
        }
      },
      pageSize: {
        serializedName: "pageSize",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ModelInformation: msRest.CompositeMapper = {
  serializedName: "ModelInformation",
  type: {
    name: "Composite",
    className: "ModelInformation",
    modelProperties: {
      comment: {
        serializedName: "comment",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "displayName",
        type: {
          name: "String"
        }
      },
      urnId: {
        serializedName: "urnId",
        type: {
          name: "String"
        }
      },
      modelName: {
        serializedName: "modelName",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "Number"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      etag: {
        serializedName: "etag",
        type: {
          name: "String"
        }
      },
      publisherId: {
        serializedName: "publisherId",
        type: {
          name: "String"
        }
      },
      publisherName: {
        serializedName: "publisherName",
        type: {
          name: "String"
        }
      },
      createdOn: {
        serializedName: "createdOn",
        type: {
          name: "DateTime"
        }
      },
      updatedOn: {
        serializedName: "updatedOn",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const SearchResponse: msRest.CompositeMapper = {
  serializedName: "SearchResponse",
  type: {
    name: "Composite",
    className: "SearchResponse",
    modelProperties: {
      continuationToken: {
        serializedName: "continuationToken",
        type: {
          name: "String"
        }
      },
      results: {
        serializedName: "results",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ModelInformation"
            }
          }
        }
      }
    }
  }
};

export const GetModelHeaders: msRest.CompositeMapper = {
  serializedName: "getmodel-headers",
  type: {
    name: "Composite",
    className: "GetModelHeaders",
    modelProperties: {
      xMsRequestId: {
        serializedName: "x-ms-request-id",
        type: {
          name: "String"
        }
      },
      eTag: {
        serializedName: "etag",
        type: {
          name: "String"
        }
      },
      xMsModelId: {
        serializedName: "x-ms-model-id",
        type: {
          name: "String"
        }
      },
      xMsModelPublisherId: {
        serializedName: "x-ms-model-publisher-id",
        type: {
          name: "String"
        }
      },
      xMsModelPublisherName: {
        serializedName: "x-ms-model-publisher-name",
        type: {
          name: "String"
        }
      },
      xMsModelCreatedon: {
        serializedName: "x-ms-model-createdon",
        type: {
          name: "DateTime"
        }
      },
      xMsModelLastupdated: {
        serializedName: "x-ms-model-lastupdated",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const CreateOrUpdateModelHeaders: msRest.CompositeMapper = {
  serializedName: "createorupdatemodel-headers",
  type: {
    name: "Composite",
    className: "CreateOrUpdateModelHeaders",
    modelProperties: {
      xMsRequestId: {
        serializedName: "x-ms-request-id",
        type: {
          name: "String"
        }
      },
      eTag: {
        serializedName: "etag",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const DeleteModelHeaders: msRest.CompositeMapper = {
  serializedName: "deletemodel-headers",
  type: {
    name: "Composite",
    className: "DeleteModelHeaders",
    modelProperties: {
      xMsRequestId: {
        serializedName: "x-ms-request-id",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchModelHeaders: msRest.CompositeMapper = {
  serializedName: "searchmodel-headers",
  type: {
    name: "Composite",
    className: "SearchModelHeaders",
    modelProperties: {
      xMsRequestId: {
        serializedName: "x-ms-request-id",
        type: {
          name: "String"
        }
      }
    }
  }
};
