/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as Parameters from "./models/parameters";
import { DigitalTwinRepositoryServiceContext } from "./digitalTwinRepositoryServiceContext";

class DigitalTwinRepositoryService extends DigitalTwinRepositoryServiceContext {
  /**
   * Initializes a new instance of the DigitalTwinRepositoryService class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.DigitalTwinRepositoryServiceOptions) {
    super(credentials, options);
  }

  /**
   * @summary Returns a DigitalTwin model object for the given \"id\".\r\nIf \"expand\" is present in
   * the query parameters and \"id\" is for a capability model then it returns\r\nthe capability
   * model with expanded interface definitions.
   * @param modelId Model id Ex: <example>urn:contoso:com:temparaturesensor:1</example>
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param [options] The optional parameters
   * @returns Promise<Models.GetModelResponse>
   */
  getModel(modelId: string, apiVersion: string, options?: Models.DigitalTwinRepositoryServiceGetModelOptionalParams): Promise<Models.GetModelResponse>;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:com:temparaturesensor:1</example>
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param callback The callback
   */
  getModel(modelId: string, apiVersion: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:com:temparaturesensor:1</example>
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param options The optional parameters
   * @param callback The callback
   */
  getModel(modelId: string, apiVersion: string, options: Models.DigitalTwinRepositoryServiceGetModelOptionalParams, callback: msRest.ServiceCallback<any>): void;
  getModel(modelId: string, apiVersion: string, options?: Models.DigitalTwinRepositoryServiceGetModelOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.GetModelResponse> {
    return this.sendOperationRequest(
      {
        modelId,
        apiVersion,
        options
      },
      getModelOperationSpec,
      callback) as Promise<Models.GetModelResponse>;
  }

  /**
   * @summary Creates or updates the DigitalTwin Model in the repository.
   * @param modelId Model id Ex: <example>urn:contoso:TemparatureSensor:1</example>
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param content Model definition in Digital Twin Definition Language format.
   * @param [options] The optional parameters
   * @returns Promise<Models.CreateOrUpdateMetamodelResponse>
   */
  createOrUpdateMetamodel(modelId: string, apiVersion: string, content: any, options?: Models.DigitalTwinRepositoryServiceCreateOrUpdateMetamodelOptionalParams): Promise<Models.CreateOrUpdateMetamodelResponse>;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:TemparatureSensor:1</example>
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param content Model definition in Digital Twin Definition Language format.
   * @param callback The callback
   */
  createOrUpdateMetamodel(modelId: string, apiVersion: string, content: any, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:TemparatureSensor:1</example>
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param content Model definition in Digital Twin Definition Language format.
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdateMetamodel(modelId: string, apiVersion: string, content: any, options: Models.DigitalTwinRepositoryServiceCreateOrUpdateMetamodelOptionalParams, callback: msRest.ServiceCallback<void>): void;
  createOrUpdateMetamodel(modelId: string, apiVersion: string, content: any, options?: Models.DigitalTwinRepositoryServiceCreateOrUpdateMetamodelOptionalParams | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<Models.CreateOrUpdateMetamodelResponse> {
    return this.sendOperationRequest(
      {
        modelId,
        apiVersion,
        content,
        options
      },
      createOrUpdateMetamodelOperationSpec,
      callback) as Promise<Models.CreateOrUpdateMetamodelResponse>;
  }

  /**
   * @summary Deletes a digital twin model from the repository.
   * @param modelId Model id Ex: <example>urn:contoso:com:temparaturesensor:1</example>
   * @param repositoryId To access private repo, repositoryId is the repo id. Delete is not allowed
   * for public repository.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param [options] The optional parameters
   * @returns Promise<Models.DeleteMetamodelResponse>
   */
  deleteMetamodel(modelId: string, repositoryId: string, apiVersion: string, options?: Models.DigitalTwinRepositoryServiceDeleteMetamodelOptionalParams): Promise<Models.DeleteMetamodelResponse>;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:com:temparaturesensor:1</example>
   * @param repositoryId To access private repo, repositoryId is the repo id. Delete is not allowed
   * for public repository.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param callback The callback
   */
  deleteMetamodel(modelId: string, repositoryId: string, apiVersion: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:com:temparaturesensor:1</example>
   * @param repositoryId To access private repo, repositoryId is the repo id. Delete is not allowed
   * for public repository.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMetamodel(modelId: string, repositoryId: string, apiVersion: string, options: Models.DigitalTwinRepositoryServiceDeleteMetamodelOptionalParams, callback: msRest.ServiceCallback<void>): void;
  deleteMetamodel(modelId: string, repositoryId: string, apiVersion: string, options?: Models.DigitalTwinRepositoryServiceDeleteMetamodelOptionalParams | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<Models.DeleteMetamodelResponse> {
    return this.sendOperationRequest(
      {
        modelId,
        repositoryId,
        apiVersion,
        options
      },
      deleteMetamodelOperationSpec,
      callback) as Promise<Models.DeleteMetamodelResponse>;
  }

  /**
   * @summary Searches pnp models for given search options.
   * It searches in the "Description, DisplayName, Comment and Id" metadata.
   * @param searchOptions Set SearchOption.searchKeyword to search models with the keyword.
   * Set the "SearchOptions.modelFilterType" to restrict to a type of DigitalTwin model (Ex:
   * Interface or CapabilityModel).
   * Default it returns all the models.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param [options] The optional parameters
   * @returns Promise<Models.SearchResponse2>
   */
  search(searchOptions: Models.SearchOptions, apiVersion: string, options?: Models.DigitalTwinRepositoryServiceSearchOptionalParams): Promise<Models.SearchResponse2>;
  /**
   * @param searchOptions Set SearchOption.searchKeyword to search models with the keyword.
   * Set the "SearchOptions.modelFilterType" to restrict to a type of DigitalTwin model (Ex:
   * Interface or CapabilityModel).
   * Default it returns all the models.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param callback The callback
   */
  search(searchOptions: Models.SearchOptions, apiVersion: string, callback: msRest.ServiceCallback<Models.SearchResponse>): void;
  /**
   * @param searchOptions Set SearchOption.searchKeyword to search models with the keyword.
   * Set the "SearchOptions.modelFilterType" to restrict to a type of DigitalTwin model (Ex:
   * Interface or CapabilityModel).
   * Default it returns all the models.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param options The optional parameters
   * @param callback The callback
   */
  search(searchOptions: Models.SearchOptions, apiVersion: string, options: Models.DigitalTwinRepositoryServiceSearchOptionalParams, callback: msRest.ServiceCallback<Models.SearchResponse>): void;
  search(searchOptions: Models.SearchOptions, apiVersion: string, options?: Models.DigitalTwinRepositoryServiceSearchOptionalParams | msRest.ServiceCallback<Models.SearchResponse>, callback?: msRest.ServiceCallback<Models.SearchResponse>): Promise<Models.SearchResponse2> {
    return this.sendOperationRequest(
      {
        searchOptions,
        apiVersion,
        options
      },
      searchOperationSpec,
      callback) as Promise<Models.SearchResponse2>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getModelOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "models/{modelId}",
  urlParameters: [
    Parameters.modelId
  ],
  queryParameters: [
    Parameters.repositoryId0,
    Parameters.apiVersion,
    Parameters.expand
  ],
  headerParameters: [
    Parameters.xMsClientRequestId
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.GetModelHeaders
    },
    default: {}
  },
  serializer
};

const createOrUpdateMetamodelOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "models/{modelId}",
  urlParameters: [
    Parameters.modelId
  ],
  queryParameters: [
    Parameters.repositoryId0,
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.xMsClientRequestId,
    Parameters.ifMatch
  ],
  requestBody: {
    parameterPath: "content",
    mapper: {
      required: true,
      serializedName: "content",
      type: {
        name: "Object"
      }
    }
  },
  responses: {
    201: {
      headersMapper: Mappers.CreateOrUpdateMetamodelHeaders
    },
    204: {
      headersMapper: Mappers.CreateOrUpdateMetamodelHeaders
    },
    412: {
      headersMapper: Mappers.CreateOrUpdateMetamodelHeaders
    },
    default: {}
  },
  serializer
};

const deleteMetamodelOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "models/{modelId}",
  urlParameters: [
    Parameters.modelId
  ],
  queryParameters: [
    Parameters.repositoryId1,
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.xMsClientRequestId
  ],
  responses: {
    204: {
      headersMapper: Mappers.DeleteMetamodelHeaders
    },
    default: {}
  },
  serializer
};

const searchOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "models/search",
  queryParameters: [
    Parameters.repositoryId0,
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.xMsClientRequestId
  ],
  requestBody: {
    parameterPath: "searchOptions",
    mapper: {
      ...Mappers.SearchOptions,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.SearchResponse,
      headersMapper: Mappers.SearchHeaders
    },
    default: {}
  },
  serializer
};

export {
  DigitalTwinRepositoryService,
  DigitalTwinRepositoryServiceContext,
  Models as DigitalTwinRepositoryServiceModels,
  Mappers as DigitalTwinRepositoryServiceMappers
};
