/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/digitalTwinMappers";
import * as Parameters from "../models/parameters";
import { IotHubGatewayServiceAPIsContext } from "../iotHubGatewayServiceAPIsContext";

/** Class representing a DigitalTwin. */
export class DigitalTwin {
  private readonly client: IotHubGatewayServiceAPIsContext;

  /**
   * Create a DigitalTwin.
   * @param {IotHubGatewayServiceAPIsContext} client Reference to the service client.
   */
  constructor(client: IotHubGatewayServiceAPIsContext) {
    this.client = client;
  }

  /**
   * @summary Gets the digital twin.
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetDigitalTwinResponse>
   */
  getDigitalTwin(digitalTwinId: string, options?: msRest.RequestOptionsBase): Promise<Models.DigitalTwinGetDigitalTwinResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param callback The callback
   */
  getDigitalTwin(digitalTwinId: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param options The optional parameters
   * @param callback The callback
   */
  getDigitalTwin(digitalTwinId: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  getDigitalTwin(digitalTwinId: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinGetDigitalTwinResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        options
      },
      getDigitalTwinOperationSpec,
      callback) as Promise<Models.DigitalTwinGetDigitalTwinResponse>;
  }

  /**
   * @summary Updates the digital twin.
   * @param digitalTwinId ID of digital twin.
   * @param digitalTwinPatch json-patch contents to update.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinUpdateDigitalTwinResponse>
   */
  updateDigitalTwin(digitalTwinId: string, digitalTwinPatch: Models.DigitalTwinPatch, options?: Models.DigitalTwinUpdateDigitalTwinOptionalParams): Promise<Models.DigitalTwinUpdateDigitalTwinResponse>;
  /**
   * @param digitalTwinId ID of digital twin.
   * @param digitalTwinPatch json-patch contents to update.
   * @param callback The callback
   */
  updateDigitalTwin(digitalTwinId: string, digitalTwinPatch: Models.DigitalTwinPatch, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param digitalTwinId ID of digital twin.
   * @param digitalTwinPatch json-patch contents to update.
   * @param options The optional parameters
   * @param callback The callback
   */
  updateDigitalTwin(digitalTwinId: string, digitalTwinPatch: Models.DigitalTwinPatch, options: Models.DigitalTwinUpdateDigitalTwinOptionalParams, callback: msRest.ServiceCallback<any>): void;
  updateDigitalTwin(digitalTwinId: string, digitalTwinPatch: Models.DigitalTwinPatch, options?: Models.DigitalTwinUpdateDigitalTwinOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinUpdateDigitalTwinResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        digitalTwinPatch,
        options
      },
      updateDigitalTwinOperationSpec,
      callback) as Promise<Models.DigitalTwinUpdateDigitalTwinResponse>;
  }

  /**
   * Invoke a digital twin  command.
   * @summary Invoke a digital twin command.
   * @param digitalTwinId
   * @param componentName
   * @param commandName
   * @param payload
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinInvokeComponentCommandResponse>
   */
  invokeComponentCommand(digitalTwinId: string, componentName: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeComponentCommandOptionalParams): Promise<Models.DigitalTwinInvokeComponentCommandResponse>;
  /**
   * @param digitalTwinId
   * @param componentName
   * @param commandName
   * @param payload
   * @param callback The callback
   */
  invokeComponentCommand(digitalTwinId: string, componentName: string, commandName: string, payload: any, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param digitalTwinId
   * @param componentName
   * @param commandName
   * @param payload
   * @param options The optional parameters
   * @param callback The callback
   */
  invokeComponentCommand(digitalTwinId: string, componentName: string, commandName: string, payload: any, options: Models.DigitalTwinInvokeComponentCommandOptionalParams, callback: msRest.ServiceCallback<any>): void;
  invokeComponentCommand(digitalTwinId: string, componentName: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeComponentCommandOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinInvokeComponentCommandResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        componentName,
        commandName,
        payload,
        options
      },
      invokeComponentCommandOperationSpec,
      callback) as Promise<Models.DigitalTwinInvokeComponentCommandResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getDigitalTwinOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitaltwins/{digitalTwinId}",
  urlParameters: [
    Parameters.digitalTwinId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      }
    },
    default: {}
  },
  serializer
};

const updateDigitalTwinOperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "digitaltwins/{digitalTwinId}",
  urlParameters: [
    Parameters.digitalTwinId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.ifMatch
  ],
  requestBody: {
    parameterPath: "digitalTwinPatch",
    mapper: {
      ...Mappers.DigitalTwinPatch,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      }
    },
    202: {},
    default: {}
  },
  serializer
};

const invokeComponentCommandOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "digitalTwins/{digitalTwinId}/components/{componentName}/commands/{commandName}",
  urlParameters: [
    Parameters.digitalTwinId,
    Parameters.componentName,
    Parameters.commandName
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.connectTimeoutInSeconds,
    Parameters.responseTimeoutInSeconds
  ],
  requestBody: {
    parameterPath: "payload",
    mapper: {
      required: true,
      serializedName: "payload",
      type: {
        name: "Object"
      }
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.DigitalTwinInvokeComponentCommandHeaders
    },
    default: {}
  },
  serializer
};
