/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/digitalTwinMappers";
import * as Parameters from "../models/parameters";
import { IotHubGatewayServiceAPIsContext } from "../iotHubGatewayServiceAPIsContext";

/** Class representing a DigitalTwin. */
export class DigitalTwin {
  private readonly client: IotHubGatewayServiceAPIsContext;

  /**
   * Create a DigitalTwin.
   * @param {IotHubGatewayServiceAPIsContext} client Reference to the service client.
   */
  constructor(client: IotHubGatewayServiceAPIsContext) {
    this.client = client;
  }

  /**
   * For IoT Hub VNET related
   * features(https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support) please use API
   * version '2020-03-13'.These features are currently in general availability in the East US, West
   * US 2, and Southcentral US regions only. We are actively working to expand the availability of
   * these features to all regions by end of month May. For rest of the APIs please continue using
   * API version '2019-10-01'
   * @summary Gets a digital twin.
   * @param id Digital Twin ID.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetDigitalTwinResponse>
   */
  getDigitalTwin(id: string, options?: msRest.RequestOptionsBase): Promise<Models.DigitalTwinGetDigitalTwinResponse>;
  /**
   * @param id Digital Twin ID.
   * @param callback The callback
   */
  getDigitalTwin(id: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param id Digital Twin ID.
   * @param options The optional parameters
   * @param callback The callback
   */
  getDigitalTwin(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  getDigitalTwin(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinGetDigitalTwinResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      getDigitalTwinOperationSpec,
      callback) as Promise<Models.DigitalTwinGetDigitalTwinResponse>;
  }

  /**
   * For IoT Hub VNET related
   * features(https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support) please use API
   * version '2020-03-13'.These features are currently in general availability in the East US, West
   * US 2, and Southcentral US regions only. We are actively working to expand the availability of
   * these features to all regions by end of month May. For rest of the APIs please continue using
   * API version '2019-10-01'
   * @summary Updates a digital twin.
   * @param id Digital Twin ID.
   * @param digitalTwinPatch json-patch contents to update.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinUpdateDigitalTwinResponse>
   */
  updateDigitalTwin(id: string, digitalTwinPatch: any[], options?: Models.DigitalTwinUpdateDigitalTwinOptionalParams): Promise<Models.DigitalTwinUpdateDigitalTwinResponse>;
  /**
   * @param id Digital Twin ID.
   * @param digitalTwinPatch json-patch contents to update.
   * @param callback The callback
   */
  updateDigitalTwin(id: string, digitalTwinPatch: any[], callback: msRest.ServiceCallback<void>): void;
  /**
   * @param id Digital Twin ID.
   * @param digitalTwinPatch json-patch contents to update.
   * @param options The optional parameters
   * @param callback The callback
   */
  updateDigitalTwin(id: string, digitalTwinPatch: any[], options: Models.DigitalTwinUpdateDigitalTwinOptionalParams, callback: msRest.ServiceCallback<void>): void;
  updateDigitalTwin(id: string, digitalTwinPatch: any[], options?: Models.DigitalTwinUpdateDigitalTwinOptionalParams | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<Models.DigitalTwinUpdateDigitalTwinResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        digitalTwinPatch,
        options
      },
      updateDigitalTwinOperationSpec,
      callback) as Promise<Models.DigitalTwinUpdateDigitalTwinResponse>;
  }

  /**
   * For IoT Hub VNET related
   * features(https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support) please use API
   * version '2020-03-13'.These features are currently in general availability in the East US, West
   * US 2, and Southcentral US regions only. We are actively working to expand the availability of
   * these features to all regions by end of month May. For rest of the APIs please continue using
   * API version '2019-10-01'
   * @summary Gets the list of interfaces.
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetComponentsResponse>
   */
  getComponents(digitalTwinId: string, options?: msRest.RequestOptionsBase): Promise<Models.DigitalTwinGetComponentsResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param callback The callback
   */
  getComponents(digitalTwinId: string, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param options The optional parameters
   * @param callback The callback
   */
  getComponents(digitalTwinId: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  getComponents(digitalTwinId: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DigitalTwinInterfaces>, callback?: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): Promise<Models.DigitalTwinGetComponentsResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        options
      },
      getComponentsOperationSpec,
      callback) as Promise<Models.DigitalTwinGetComponentsResponse>;
  }

  /**
   * For IoT Hub VNET related
   * features(https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support) please use API
   * version '2020-03-13'.These features are currently in general availability in the East US, West
   * US 2, and Southcentral US regions only. We are actively working to expand the availability of
   * these features to all regions by end of month May. For rest of the APIs please continue using
   * API version '2019-10-01'
   * @summary Updates desired properties of multiple interfaces.
   * Example URI: "digitalTwins/{digitalTwinId}/interfaces"
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param interfacesPatchInfo Multiple interfaces desired properties to update.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinUpdateComponentResponse>
   */
  updateComponent(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, options?: Models.DigitalTwinUpdateComponentOptionalParams): Promise<Models.DigitalTwinUpdateComponentResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param interfacesPatchInfo Multiple interfaces desired properties to update.
   * @param callback The callback
   */
  updateComponent(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param interfacesPatchInfo Multiple interfaces desired properties to update.
   * @param options The optional parameters
   * @param callback The callback
   */
  updateComponent(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, options: Models.DigitalTwinUpdateComponentOptionalParams, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  updateComponent(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, options?: Models.DigitalTwinUpdateComponentOptionalParams | msRest.ServiceCallback<Models.DigitalTwinInterfaces>, callback?: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): Promise<Models.DigitalTwinUpdateComponentResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        interfacesPatchInfo,
        options
      },
      updateComponentOperationSpec,
      callback) as Promise<Models.DigitalTwinUpdateComponentResponse>;
  }

  /**
   * For IoT Hub VNET related
   * features(https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support) please use API
   * version '2020-03-13'.These features are currently in general availability in the East US, West
   * US 2, and Southcentral US regions only. We are actively working to expand the availability of
   * these features to all regions by end of month May. For rest of the APIs please continue using
   * API version '2019-10-01'
   * @summary Gets the interface of given interfaceId.
   * Example URI: "digitalTwins/{digitalTwinId}/interfaces/{interfaceName}"
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param interfaceName The interface name.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetComponentResponse>
   */
  getComponent(digitalTwinId: string, interfaceName: string, options?: msRest.RequestOptionsBase): Promise<Models.DigitalTwinGetComponentResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param interfaceName The interface name.
   * @param callback The callback
   */
  getComponent(digitalTwinId: string, interfaceName: string, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * @param interfaceName The interface name.
   * @param options The optional parameters
   * @param callback The callback
   */
  getComponent(digitalTwinId: string, interfaceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  getComponent(digitalTwinId: string, interfaceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DigitalTwinInterfaces>, callback?: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): Promise<Models.DigitalTwinGetComponentResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        interfaceName,
        options
      },
      getComponentOperationSpec,
      callback) as Promise<Models.DigitalTwinGetComponentResponse>;
  }

  /**
   * For IoT Hub VNET related
   * features(https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support) please use API
   * version '2020-03-13'.These features are currently in general availability in the East US, West
   * US 2, and Southcentral US regions only. We are actively working to expand the availability of
   * these features to all regions by end of month May. For rest of the APIs please continue using
   * API version '2019-10-01'
   * @summary Returns a DigitalTwin model definition for the given id.
   * If "expand" is present in the query parameters and id is for a device capability model then it
   * returns
   * the capability metamodel with expanded interface definitions.
   * @param modelId Model id Ex: <example>urn:contoso:TemperatureSensor:1</example>
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetDigitalTwinModelResponse>
   */
  getDigitalTwinModel(modelId: string, options?: Models.DigitalTwinGetDigitalTwinModelOptionalParams): Promise<Models.DigitalTwinGetDigitalTwinModelResponse>;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:TemperatureSensor:1</example>
   * @param callback The callback
   */
  getDigitalTwinModel(modelId: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:TemperatureSensor:1</example>
   * @param options The optional parameters
   * @param callback The callback
   */
  getDigitalTwinModel(modelId: string, options: Models.DigitalTwinGetDigitalTwinModelOptionalParams, callback: msRest.ServiceCallback<any>): void;
  getDigitalTwinModel(modelId: string, options?: Models.DigitalTwinGetDigitalTwinModelOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinGetDigitalTwinModelResponse> {
    return this.client.sendOperationRequest(
      {
        modelId,
        options
      },
      getDigitalTwinModelOperationSpec,
      callback) as Promise<Models.DigitalTwinGetDigitalTwinModelResponse>;
  }

  /**
   * Invoke a digital twin interface command.
   * @summary Invoke a digital twin interface command.
   * @param digitalTwinId
   * @param interfaceName
   * @param commandName
   * @param payload
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinInvokeComponentCommandResponse>
   */
  invokeComponentCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeComponentCommandOptionalParams): Promise<Models.DigitalTwinInvokeComponentCommandResponse>;
  /**
   * @param digitalTwinId
   * @param interfaceName
   * @param commandName
   * @param payload
   * @param callback The callback
   */
  invokeComponentCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param digitalTwinId
   * @param interfaceName
   * @param commandName
   * @param payload
   * @param options The optional parameters
   * @param callback The callback
   */
  invokeComponentCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, options: Models.DigitalTwinInvokeComponentCommandOptionalParams, callback: msRest.ServiceCallback<any>): void;
  invokeComponentCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeComponentCommandOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinInvokeComponentCommandResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        interfaceName,
        commandName,
        payload,
        options
      },
      invokeComponentCommandOperationSpec,
      callback) as Promise<Models.DigitalTwinInvokeComponentCommandResponse>;
  }

  /**
   * Invoke a digital twin command.
   * @summary Invoke a digital twin command.
   * @param id
   * @param componentPath
   * @param commandName
   * @param payload
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinInvokeComponentCommandV2Response>
   */
  invokeComponentCommandV2(id: string, componentPath: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeComponentCommandV2OptionalParams): Promise<Models.DigitalTwinInvokeComponentCommandV2Response>;
  /**
   * @param id
   * @param componentPath
   * @param commandName
   * @param payload
   * @param callback The callback
   */
  invokeComponentCommandV2(id: string, componentPath: string, commandName: string, payload: any, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param id
   * @param componentPath
   * @param commandName
   * @param payload
   * @param options The optional parameters
   * @param callback The callback
   */
  invokeComponentCommandV2(id: string, componentPath: string, commandName: string, payload: any, options: Models.DigitalTwinInvokeComponentCommandV2OptionalParams, callback: msRest.ServiceCallback<any>): void;
  invokeComponentCommandV2(id: string, componentPath: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeComponentCommandV2OptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinInvokeComponentCommandV2Response> {
    return this.client.sendOperationRequest(
      {
        id,
        componentPath,
        commandName,
        payload,
        options
      },
      invokeComponentCommandV2OperationSpec,
      callback) as Promise<Models.DigitalTwinInvokeComponentCommandV2Response>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getDigitalTwinOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitaltwins/{id}",
  urlParameters: [
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.DigitalTwinGetDigitalTwinHeaders
    },
    default: {}
  },
  serializer
};

const updateDigitalTwinOperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "digitaltwins/{id}",
  urlParameters: [
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.ifMatch
  ],
  requestBody: {
    parameterPath: "digitalTwinPatch",
    mapper: {
      required: true,
      serializedName: "digitalTwinPatch",
      type: {
        name: "Sequence",
        element: {
          type: {
            name: "Object"
          }
        }
      }
    }
  },
  responses: {
    202: {
      headersMapper: Mappers.DigitalTwinUpdateDigitalTwinHeaders
    },
    default: {}
  },
  serializer
};

const getComponentsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitalTwins/{digitalTwinId}/interfaces",
  urlParameters: [
    Parameters.digitalTwinId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DigitalTwinInterfaces,
      headersMapper: Mappers.DigitalTwinGetComponentsHeaders
    },
    default: {}
  },
  serializer
};

const updateComponentOperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "digitalTwins/{digitalTwinId}/interfaces",
  urlParameters: [
    Parameters.digitalTwinId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.ifMatch
  ],
  requestBody: {
    parameterPath: "interfacesPatchInfo",
    mapper: {
      ...Mappers.DigitalTwinInterfacesPatch,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.DigitalTwinInterfaces,
      headersMapper: Mappers.DigitalTwinUpdateComponentHeaders
    },
    default: {}
  },
  serializer
};

const getComponentOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitalTwins/{digitalTwinId}/interfaces/{interfaceName}",
  urlParameters: [
    Parameters.digitalTwinId,
    Parameters.interfaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DigitalTwinInterfaces,
      headersMapper: Mappers.DigitalTwinGetComponentHeaders
    },
    default: {}
  },
  serializer
};

const getDigitalTwinModelOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitalTwins/models/{modelId}",
  urlParameters: [
    Parameters.modelId
  ],
  queryParameters: [
    Parameters.expand,
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.DigitalTwinGetDigitalTwinModelHeaders
    },
    204: {
      headersMapper: Mappers.DigitalTwinGetDigitalTwinModelHeaders
    },
    default: {}
  },
  serializer
};

const invokeComponentCommandOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "digitalTwins/{digitalTwinId}/interfaces/{interfaceName}/commands/{commandName}",
  urlParameters: [
    Parameters.digitalTwinId,
    Parameters.interfaceName,
    Parameters.commandName
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.connectTimeoutInSeconds,
    Parameters.responseTimeoutInSeconds
  ],
  requestBody: {
    parameterPath: "payload",
    mapper: {
      required: true,
      serializedName: "payload",
      type: {
        name: "Object"
      }
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.DigitalTwinInvokeComponentCommandHeaders
    },
    default: {}
  },
  serializer
};

const invokeComponentCommandV2OperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "digitaltwins/{id}/components/{componentPath}/commands/{commandName}",
  urlParameters: [
    Parameters.id,
    Parameters.componentPath,
    Parameters.commandName
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.connectTimeoutInSeconds,
    Parameters.responseTimeoutInSeconds
  ],
  requestBody: {
    parameterPath: "payload",
    mapper: {
      required: true,
      serializedName: "payload",
      type: {
        name: "Object"
      }
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.DigitalTwinInvokeComponentCommandV2Headers
    },
    default: {}
  },
  serializer
};
