/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/httpRuntimeMappers";
import * as Parameters from "../models/parameters";
import { IotHubGatewayServiceAPIsContext } from "../iotHubGatewayServiceAPIsContext";

/** Class representing a HttpRuntime. */
export class HttpRuntime {
  private readonly client: IotHubGatewayServiceAPIsContext;

  /**
   * Create a HttpRuntime.
   * @param {IotHubGatewayServiceAPIsContext} client Reference to the service client.
   */
  constructor(client: IotHubGatewayServiceAPIsContext) {
    this.client = client;
  }

  /**
   * This method is used to retrieve feedback of a cloud-to-device message See
   * https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messaging for more information. This
   * capability is only available in the standard tier IoT Hub. For more information, see [Choose the
   * right IoT Hub tier](https://aka.ms/scaleyouriotsolution).
   * @summary This method is used to retrieve feedback of a cloud-to-device message.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  receiveFeedbackNotification(options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param callback The callback
   */
  receiveFeedbackNotification(callback: msRest.ServiceCallback<void>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  receiveFeedbackNotification(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  receiveFeedbackNotification(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      receiveFeedbackNotificationOperationSpec,
      callback);
  }

  /**
   * This method completes a feedback message. The lockToken obtained when the message was received
   * must be provided to resolve race conditions when completing, a feedback message. A completed
   * message is deleted from the feedback queue. See
   * https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messaging for more information.
   * @summary This method completes a feedback message.
   * @param lockToken Lock token.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  completeFeedbackNotification(lockToken: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param lockToken Lock token.
   * @param callback The callback
   */
  completeFeedbackNotification(lockToken: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param lockToken Lock token.
   * @param options The optional parameters
   * @param callback The callback
   */
  completeFeedbackNotification(lockToken: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  completeFeedbackNotification(lockToken: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        lockToken,
        options
      },
      completeFeedbackNotificationOperationSpec,
      callback);
  }

  /**
   * This method abandons a feedback message. The lockToken obtained when the message was received
   * must be provided to resolve race conditions when abandoning, a feedback message. A abandoned
   * message is deleted from the feedback queue. See
   * https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messaging for more information.
   * @summary This method abandons a feedback message.
   * @param lockToken Lock Token.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  abandonFeedbackNotification(lockToken: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param lockToken Lock Token.
   * @param callback The callback
   */
  abandonFeedbackNotification(lockToken: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param lockToken Lock Token.
   * @param options The optional parameters
   * @param callback The callback
   */
  abandonFeedbackNotification(lockToken: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  abandonFeedbackNotification(lockToken: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        lockToken,
        options
      },
      abandonFeedbackNotificationOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const receiveFeedbackNotificationOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "messages/serviceBound/feedback",
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {},
    204: {},
    default: {}
  },
  serializer
};

const completeFeedbackNotificationOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "messages/serviceBound/feedback/{lockToken}",
  urlParameters: [
    Parameters.lockToken
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    204: {},
    default: {}
  },
  serializer
};

const abandonFeedbackNotificationOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "messages/serviceBound/feedback/{lockToken}/abandon",
  urlParameters: [
    Parameters.lockToken
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    204: {},
    default: {}
  },
  serializer
};
