/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/jobClientMappers";
import * as Parameters from "../models/parameters";
import { IotHubGatewayServiceAPIsContext } from "../iotHubGatewayServiceAPIsContext";

/** Class representing a JobClient. */
export class JobClient {
  private readonly client: IotHubGatewayServiceAPIsContext;

  /**
   * Create a JobClient.
   * @param {IotHubGatewayServiceAPIsContext} client Reference to the service client.
   */
  constructor(client: IotHubGatewayServiceAPIsContext) {
    this.client = client;
  }

  /**
   * Create a new import/export job on an IoT hub. See
   * https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#import-and-export-device-identities
   * for more information.
   * @summary Create a new import/export job on an IoT hub.
   * @param jobProperties Specifies the job specification.
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientCreateImportExportJobResponse>
   */
  createImportExportJob(jobProperties: Models.JobProperties, options?: msRest.RequestOptionsBase): Promise<Models.JobClientCreateImportExportJobResponse>;
  /**
   * @param jobProperties Specifies the job specification.
   * @param callback The callback
   */
  createImportExportJob(jobProperties: Models.JobProperties, callback: msRest.ServiceCallback<Models.JobProperties>): void;
  /**
   * @param jobProperties Specifies the job specification.
   * @param options The optional parameters
   * @param callback The callback
   */
  createImportExportJob(jobProperties: Models.JobProperties, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JobProperties>): void;
  createImportExportJob(jobProperties: Models.JobProperties, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JobProperties>, callback?: msRest.ServiceCallback<Models.JobProperties>): Promise<Models.JobClientCreateImportExportJobResponse> {
    return this.client.sendOperationRequest(
      {
        jobProperties,
        options
      },
      createImportExportJobOperationSpec,
      callback) as Promise<Models.JobClientCreateImportExportJobResponse>;
  }

  /**
   * Gets the status of all import/export jobs in an iot hub. See
   * https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#import-and-export-device-identities
   * for more information.
   * @summary Gets the status of all import/export jobs in an iot hub
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientGetImportExportJobsResponse>
   */
  getImportExportJobs(options?: msRest.RequestOptionsBase): Promise<Models.JobClientGetImportExportJobsResponse>;
  /**
   * @param callback The callback
   */
  getImportExportJobs(callback: msRest.ServiceCallback<Models.JobProperties[]>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  getImportExportJobs(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JobProperties[]>): void;
  getImportExportJobs(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JobProperties[]>, callback?: msRest.ServiceCallback<Models.JobProperties[]>): Promise<Models.JobClientGetImportExportJobsResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      getImportExportJobsOperationSpec,
      callback) as Promise<Models.JobClientGetImportExportJobsResponse>;
  }

  /**
   * Gets the status of an import or export job in an iot hub. See
   * https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#import-and-export-device-identities
   * for more information.
   * @summary Gets the status of an import or export job in an iot hub
   * @param id Job ID.
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientGetImportExportJobResponse>
   */
  getImportExportJob(id: string, options?: msRest.RequestOptionsBase): Promise<Models.JobClientGetImportExportJobResponse>;
  /**
   * @param id Job ID.
   * @param callback The callback
   */
  getImportExportJob(id: string, callback: msRest.ServiceCallback<Models.JobProperties>): void;
  /**
   * @param id Job ID.
   * @param options The optional parameters
   * @param callback The callback
   */
  getImportExportJob(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JobProperties>): void;
  getImportExportJob(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JobProperties>, callback?: msRest.ServiceCallback<Models.JobProperties>): Promise<Models.JobClientGetImportExportJobResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      getImportExportJobOperationSpec,
      callback) as Promise<Models.JobClientGetImportExportJobResponse>;
  }

  /**
   * Cancels an import or export job in an IoT hub. See
   * https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#import-and-export-device-identities
   * for more information.
   * @summary Cancels an import or export job in an IoT hub.
   * @param id Job ID.
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientCancelImportExportJobResponse>
   */
  cancelImportExportJob(id: string, options?: msRest.RequestOptionsBase): Promise<Models.JobClientCancelImportExportJobResponse>;
  /**
   * @param id Job ID.
   * @param callback The callback
   */
  cancelImportExportJob(id: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param id Job ID.
   * @param options The optional parameters
   * @param callback The callback
   */
  cancelImportExportJob(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  cancelImportExportJob(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.JobClientCancelImportExportJobResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      cancelImportExportJobOperationSpec,
      callback) as Promise<Models.JobClientCancelImportExportJobResponse>;
  }

  /**
   * Retrieves details of a scheduled job from an IoT hub. See
   * https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-jobs for more information.
   * @summary Retrieves details of a scheduled job from an IoT hub.
   * @param id Job ID.
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientGetJobResponse>
   */
  getJob(id: string, options?: msRest.RequestOptionsBase): Promise<Models.JobClientGetJobResponse>;
  /**
   * @param id Job ID.
   * @param callback The callback
   */
  getJob(id: string, callback: msRest.ServiceCallback<Models.JobResponse>): void;
  /**
   * @param id Job ID.
   * @param options The optional parameters
   * @param callback The callback
   */
  getJob(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JobResponse>): void;
  getJob(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JobResponse>, callback?: msRest.ServiceCallback<Models.JobResponse>): Promise<Models.JobClientGetJobResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      getJobOperationSpec,
      callback) as Promise<Models.JobClientGetJobResponse>;
  }

  /**
   * Creates a new job to schedule update twins or device direct methods on an IoT hub at a scheduled
   * time. See https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-jobs for more
   * information.
   * @summary Creates a new job to schedule update twins or device direct methods on an IoT hub at a
   * scheduled time.
   * @param id Job ID.
   * @param jobRequest
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientCreateJobResponse>
   */
  createJob(id: string, jobRequest: Models.JobRequest, options?: msRest.RequestOptionsBase): Promise<Models.JobClientCreateJobResponse>;
  /**
   * @param id Job ID.
   * @param jobRequest
   * @param callback The callback
   */
  createJob(id: string, jobRequest: Models.JobRequest, callback: msRest.ServiceCallback<Models.JobResponse>): void;
  /**
   * @param id Job ID.
   * @param jobRequest
   * @param options The optional parameters
   * @param callback The callback
   */
  createJob(id: string, jobRequest: Models.JobRequest, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JobResponse>): void;
  createJob(id: string, jobRequest: Models.JobRequest, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JobResponse>, callback?: msRest.ServiceCallback<Models.JobResponse>): Promise<Models.JobClientCreateJobResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        jobRequest,
        options
      },
      createJobOperationSpec,
      callback) as Promise<Models.JobClientCreateJobResponse>;
  }

  /**
   * Cancels a scheduled job on an IoT hub. See
   * https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-jobs for more information.
   * @summary Cancels a scheduled job on an IoT hub.
   * @param id Job ID.
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientCancelJobResponse>
   */
  cancelJob(id: string, options?: msRest.RequestOptionsBase): Promise<Models.JobClientCancelJobResponse>;
  /**
   * @param id Job ID.
   * @param callback The callback
   */
  cancelJob(id: string, callback: msRest.ServiceCallback<Models.JobResponse>): void;
  /**
   * @param id Job ID.
   * @param options The optional parameters
   * @param callback The callback
   */
  cancelJob(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JobResponse>): void;
  cancelJob(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JobResponse>, callback?: msRest.ServiceCallback<Models.JobResponse>): Promise<Models.JobClientCancelJobResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      cancelJobOperationSpec,
      callback) as Promise<Models.JobClientCancelJobResponse>;
  }

  /**
   * Query an IoT hub to retrieve information regarding jobs using the IoT Hub query language. See
   * https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language for more information.
   * Pagination of results is supported. This returns information about jobs only.
   * @summary Query an IoT hub to retrieve information regarding jobs using the IoT Hub query
   * language
   * @param [options] The optional parameters
   * @returns Promise<Models.JobClientQueryJobsResponse>
   */
  queryJobs(options?: Models.JobClientQueryJobsOptionalParams): Promise<Models.JobClientQueryJobsResponse>;
  /**
   * @param callback The callback
   */
  queryJobs(callback: msRest.ServiceCallback<Models.QueryResult>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  queryJobs(options: Models.JobClientQueryJobsOptionalParams, callback: msRest.ServiceCallback<Models.QueryResult>): void;
  queryJobs(options?: Models.JobClientQueryJobsOptionalParams | msRest.ServiceCallback<Models.QueryResult>, callback?: msRest.ServiceCallback<Models.QueryResult>): Promise<Models.JobClientQueryJobsResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      queryJobsOperationSpec,
      callback) as Promise<Models.JobClientQueryJobsResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const createImportExportJobOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "jobs/create",
  queryParameters: [
    Parameters.apiVersion
  ],
  requestBody: {
    parameterPath: "jobProperties",
    mapper: {
      ...Mappers.JobProperties,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.JobProperties
    },
    default: {}
  },
  serializer
};

const getImportExportJobsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "jobs",
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "JobProperties"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const getImportExportJobOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "jobs/{id}",
  urlParameters: [
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.JobProperties
    },
    default: {}
  },
  serializer
};

const cancelImportExportJobOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "jobs/{id}",
  urlParameters: [
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      }
    },
    204: {},
    default: {}
  },
  serializer
};

const getJobOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "jobs/v2/{id}",
  urlParameters: [
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.JobResponse
    },
    default: {}
  },
  serializer
};

const createJobOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "jobs/v2/{id}",
  urlParameters: [
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  requestBody: {
    parameterPath: "jobRequest",
    mapper: {
      ...Mappers.JobRequest,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.JobResponse
    },
    default: {}
  },
  serializer
};

const cancelJobOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "jobs/v2/{id}/cancel",
  urlParameters: [
    Parameters.id
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.JobResponse
    },
    default: {}
  },
  serializer
};

const queryJobsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "jobs/v2/query",
  queryParameters: [
    Parameters.jobType,
    Parameters.jobStatus,
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.QueryResult
    },
    default: {}
  },
  serializer
};
