name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
resources:
  - repo: self
    clean: true

stages:
- stage: setup
  jobs:
  - job: create_azure_resources
    pool:
      vmImage: 'ubuntu-24.04'
    steps:
    - script: |
        sudo apt-get install -y uuid
        # Cut first 28 characters of uuid to make a resource group name no longer than 46 characters.
        # deploy.sh fails if rgName is longer than 46 characters.
        AZURE_RESOURCE_GROUP="nodenightlylinux$(uuid | tr -d '-' | cut -c1-29)"

        # Export variables to other stages/jobs/steps.
        echo "##vso[task.setvariable variable=AZURE_RESOURCE_GROUP;isOutput=true]$AZURE_RESOURCE_GROUP"
      name: setResourceNames
      displayName: Set Resource Names

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e

          export AZURE_RESOURCE_GROUP=$(setResourceNames.AZURE_RESOURCE_GROUP)

          ./node_e2e_resources/deploy.sh -l "$AZURE_REGION" -n "$AZURE_RESOURCE_GROUP" -u
          find . -iname activate*
      displayName: Create Azure Resources
      name: createAzureResources

    - publish: ./node_e2e_resources/secrets/env/activate.cmd
      artifact: secretsEnv

- stage: build_and_tests
  jobs:
  - job: Phase_1
    displayName: 'Windows Node 14.x'
    condition: succeededOrFailed()
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: secretsEnv

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
        addToPath: true

    - task: NodeTool@0
      displayName: 'Use Node 14.x'
      inputs:
        versionSpec: '14.x'

    - powershell: |
        runas.exe /savecred /user:administrator
        npm install --global node-gyp@6.1.0
        npm install --global lerna@^6.6.2
        npm install
      displayName: 'Install Dependencies'

    - script: |
        call lerna bootstrap --hoist
        call lerna run build
      displayName: 'Bootstrap & Build'

    - script: |
        call $(Pipeline.Workspace)\secretsEnv\activate.cmd
        call lerna run ci
      displayName: 'Unit & Integration Tests'

    - script: |
        call $(Pipeline.Workspace)\secretsEnv\activate.cmd
        lerna run e2e
      displayName: 'E2E Tests'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results | Mocha'
      inputs:
        testResultsFiles: '**/test-results.*.xml'
        mergeTestResults: true
        testRunTitle: 'E2E Tests - Windows'
      condition: succeededOrFailed()

    - task: DownloadBuildArtifacts@0
      condition: coalesce(variables.release, False)
      inputs:
        buildType: 'specific'
        project: 'f9b79625-2860-4d92-a4ee-57b03fabfd10' # azure-iot-sdks
        pipeline: '296' # iot-sdks-internals-scripts pipeline
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)/scripts'
        artifactName: 'node'

    - powershell: |
        . $(System.ArtifactsDirectory)/scripts/node/release-node.ps1
        $outputFolder = $env:output
        Build-Artifacts -Sources $env:sources -Output $outputFolder
      displayName: 'npm pack'
      condition: coalesce(variables.release, False)
      env:
        sources: $(Build.SourcesDirectory)
        output: $(Build.ArtifactStagingDirectory)\_out

    - task: PublishBuildArtifacts@1
      condition: coalesce(variables.release, False)
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)\_out
        ArtifactName: drop
        publishLocation: 'Container'

    - task: AzurePowerShell@5
      displayName: 'Upload files to partner drop folder'
      condition: coalesce(variables.release, False)
      inputs:
        azureSubscription: 'azuresdkpartnerdrops'
        ScriptType: 'InlineScript'
        azurePowerShellVersion: LatestVersion 
        pwsh: true
        Inline: |
          azcopy copy $(Build.ArtifactStagingDirectory)\_out\* "https://azuresdkpartnerdrops.blob.core.windows.net/drops/azure-iot-sdk/node/" --recursive=true
      env: 
        AZCOPY_AUTO_LOGIN_TYPE: 'PSCRED'
- stage: cleanup
  dependsOn:
  - setup
  - build_and_tests
  condition: always() # Run stage even if the pipeline run is cancelled.
  jobs:
  - job: destroy_azure_resource_group
    condition: always() # Run job even if the pipeline run is cancelled.
    pool:
      vmImage: 'ubuntu-24.04'
    variables:
        AZURE_RESOURCE_GROUP: $[stageDependencies.setup.create_azure_resources.outputs['setResourceNames.AZURE_RESOURCE_GROUP']]
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # set -e

          time az group delete --name $(AZURE_RESOURCE_GROUP) --yes
      displayName: Destroy Azure Resource Group
      condition: always() # Run step even if the pipeline run is cancelled.