name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
resources:
  - repo: self
    clean: true

stages:
- stage: setup
  jobs:
  - job: create_azure_resources
    pool:
      vmImage: 'ubuntu-24.04'
    steps:
    - script: |
        sudo apt-get install -y uuid
        AZURE_RESOURCE_GROUP="nodenightlylinux$(uuid | tr -d '-')"

        # Export variables to other stages/jobs/steps.
        echo "##vso[task.setvariable variable=AZURE_RESOURCE_GROUP;isOutput=true]$AZURE_RESOURCE_GROUP"
      name: setResourceNames
      displayName: Set Resource Names

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          . ./node_e2e_resources/deploy.sh -l "$AZURE_REGION" -n "$AZURE_RESOURCE_GROUP"
      displayName: Create Azure Resources
      name: createAzureResources

    - publish: ./activate
      artifact: buildOutput

- stage: build_and_tests
  jobs:
  - job: Phase_2
    displayName: Ubuntu 22.04 - Node 14.x
    condition: succeededOrFailed()
    pool:
      vmImage: 'ubuntu-22.04'

    steps:
    - download: current
      artifact: buildOutput

    - task: NodeTool@0
      displayName: 'Use Node 14.x'
      inputs:
        versionSpec: '14.x'

    - script: |
        npm install --global node-gyp
        npm install --global lerna@^6.6.2
        npm install
      displayName: 'Install Dependencies'

    - script: |
          npx tsc --version
          lerna bootstrap --hoist
          lerna run build
      displayName: 'Bootstrap & Build'

    - script: |
        set -e
        . $(Pipeline.Workspace)/activate    # Set env vars defined in setup.
        lerna run ci
      displayName: 'Unit & Integration Tests'

    - script: |
        set -e
        . $(Pipeline.Workspace)/activate    # Set env vars defined in setup.
        lerna run e2e
      displayName: 'E2E Tests'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results | Mocha'
      inputs:
        testResultsFiles: '**/test-results.*.xml'
        mergeTestResults: true
        testRunTitle: 'E2E Tests - Linux'
      condition: succeededOrFailed()
- stage: cleanup
  dependsOn:
  - setup
  - build_and_tests
  condition: always() # Run stage even if the pipeline run is cancelled.
  jobs:
  - job: destroy_azure_resource_group
    condition: always() # Run job even if the pipeline run is cancelled.
    pool:
      vmImage: 'ubuntu-24.04'
    variables:
        AZURE_RESOURCE_GROUP: $[stageDependencies.setup.create_azure_resources.outputs['setResourceNames.AZURE_RESOURCE_GROUP']]
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # set -e

          time az group delete --name $(AZURE_RESOURCE_GROUP) --yes
      displayName: Destroy Azure Resource Group
      condition: always() # Run step even if the pipeline run is cancelled.